import os
import sys
import shutil
import subprocess
import zipfile
from pathlib import Path


def compile_strategy_package(workspace_dir: str, payload_name: str = "cloud_payload.zip") -> str:
    """
    Recursively compiles a multi-file strategy directory into secure C-extensions,
    strips the raw .py files, and packages it into a deployment-ready .zip file.
    """
    workspace_path = Path(workspace_dir)
    if not workspace_path.exists() or not workspace_path.is_dir():
        raise FileNotFoundError(f"Workspace directory not found: {workspace_dir}")

    # 1. Dynamically locate all .py files in the workspace
    py_files = list(workspace_path.rglob("*.py"))

    # Exclude any setup scripts or previous test artifacts
    py_files = [f for f in py_files if f.name != "setup_build.py"]

    if not py_files:
        raise RuntimeError(f"No Python files found to compile in {workspace_dir}")

    # Convert absolute paths to relative strings for Cython
    relative_py_files = [str(f.relative_to(workspace_path)).replace('\\', '/') for f in py_files]

    # 2. Generate the multi-file setup.py script
    setup_script_path = workspace_path / "setup_build.py"
    setup_code = f"""from setuptools import setup
from Cython.Build import cythonize

# Cythonize the entire list of discovered files
setup(
    ext_modules=cythonize(
        {relative_py_files}, 
        compiler_directives={{'language_level': "3"}}
    ),
    script_args=["build_ext", "--inplace"]
)
"""

    with open(setup_script_path, "w") as f:
        f.write(setup_code)

    # 3. Execute the Cython build process
    try:
        subprocess.run(
            [sys.executable, "setup_build.py"],
            cwd=workspace_dir,
            check=True,
            capture_output=True,
            text=True
        )
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Compilation failed:\n{e.stderr}")
    finally:
        # 4. Clean up the C-compiler artifacts
        if setup_script_path.exists():
            setup_script_path.unlink()

        build_dir = workspace_path / "build"
        if build_dir.exists():
            shutil.rmtree(build_dir)

        # Delete the intermediate .c files generated by Cython
        for c_file in workspace_path.rglob("*.c"):
            c_file.unlink()

    # 5. Package the Secure Payload (.zip)
    payload_path = workspace_path / payload_name

    with zipfile.ZipFile(payload_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for file_path in workspace_path.rglob("*"):
            if file_path.is_file():
                # SECURITY FIREWALL: Do NOT zip raw .py files!
                if file_path.suffix == '.py':
                    continue

                # Exclude the zip file itself so we don't create an infinite loop
                if file_path.name == payload_name:
                    continue

                # Write the file to the zip archive, preserving its relative folder structure
                arcname = file_path.relative_to(workspace_path)
                zipf.write(file_path, arcname)

    return str(payload_path)